SHELL  =/bin/sh
CFLAGS = -flibrary-level 0
CC     = bspcc


all: helloworld helloworld_init helloworld_seq \
     reverse array_put array_get sum sparse
              
clean: 
	rm -f STAT.bsp PROF.bsp \
              helloworld helloworld_init helloworld_seq \
              reverse array_put array_get sum sparse *.tab
