.TH "bsp_end" 3 "1.4 25/9/98" "Oxford BSP Toolset" "BSPlib FUNCTIONS"
.SH NAME
bsp_end \- terminate BSP processes.


.SH C SYNOPSIS
.nf
.B #include \&"bsp.h\&"
.PP
.B void bsp_end()
.fi
.SH FORTRAN SYNOPSIS 
.nf
.B "SUBROUTINE bspend()
.fi

.SH DESCRIPTION
Terminate the SPMD execution of the processes spawned by
.B bsp_begin(3)\c
\&. All but process zero is terminated, and process zero is left to
continue the execution of the rest of the program sequentially.




.SH "SEE ALSO"
bsplib(3), bsp_begin(3), bsp_end(3)


.I ``BSPlib: The BSP Programming Library''
Jonathan M. D. Hill, Bill McColl, Dan C. Stefanescu, Mark W. Goudreau,
Kevin Lang, Satish B. Rao, , Torsten Suel, Thanasis Tsantilas, and Rob
Bisseling. Parallel Computing, to appear 1998. See
.I http://www.bsp-worldwide.org
for more details.

.SH BUGS
Problems and bug reports should be mailed to 
.I bsplib-bugs@comlab.ox.ac.uk

.SH AUTHORS
The Oxford BSP Toolset implementation of BSPlib was written by
Jonathan.Hill@comlab.ox.ac.uk
.br
.B http://www.comlab.ox.ac.uk/oucl/people/jonathan.hill.html


