.TH "bspshutd" 1 "1.4 25/9/98" "Oxford BSP Toolset" 
.SH NAME
bspshutd \- stop the BSPlib TCP/IP or UDP/IP daemons

.SH SYNOPSIS
.B bspshutd

.SH DESCRIPTION
Stops the daemons on each of the machines specified in the 
.I .bsptcphost
file. 

.SH  "SEE ALSO"
bsplibd(1)

The Oxford BSP toolset web pages can be found  at:
.br
.I http://www.bsp-worldwide.org/implmnts/oxtool/

.SH BUGS
Problems and bug reports should be mailed to 
.I bsplib-bugs@comlab.ox.ac.uk

.SH AUTHORS
Stephen.Donaldson@comlab.ox.ac.uk
.PP
.B http://www.comlab.ox.ac.uk/oucl/people/stephen.donaldson.html
