.TH "ipcclean" 1 "1.4 25/9/98" "Oxford BSP Toolset" 
.SH NAME
ipcclean \- cleanup the inter-process communication facilities

.SH SYNOPSIS
.BR ipcclean " [-v]"


.SH DESCRIPTION

ipcclean removes any inter-process communication facilites left behind
by a user program. The -v option shows the shared memory and
semaphores that are being cleaned

.SH "SEE ALSO"
ipcs(1), ipcrm(1)


.SH BUGS
Problems and bug reports should be mailed to 
.I bsplib-bugs@comlab.ox.ac.uk

.SH AUTHORS
Jonathan.Hill@comlab.ox.ac.uk
.br
.B http://www.comlab.ox.ac.uk/oucl/people/jonathan.hill.html


